### ISSUE TITLE
Missing displayed data for MER tiling

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#1]
When I use the following code to display the provided GeoJson  to Git : 
import geopandas as gpd
import matplotlib.pyplot as plt
gdf = gpd.read_file('/home/malapert/smt_data/git/smt-data/Surveys/mer_global_3.geojson')
gdf.boundary.plot()
plt.show()
I get the attached picture.
![mer_00_geojson](https://user-images.githubusercontent.com/2744725/100080115-ba690d00-2e45-11eb-8716-545d375ccb45.png)

When I use SMT, some polygons are missing on this area : 
![Screenshot from 2020-11-24 11-06-22](https://user-images.githubusercontent.com/2744725/100080167-ce147380-2e45-11eb-87c4-5d50932e5410.png)

**Comment by J-Christophe** [comment]
Some Ids in the GeoJson are duplicated, this could be the problem

**Comment by xalioth** [comment]
This seems to be solved in v 0.0.4
