### ISSUE TITLE
Strange behavior of the level of detail

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#10]
When zooming, the behavior of the level of detail is a bit strange : 

![Screenshot from 2020-12-17 15-41-26](https://user-images.githubusercontent.com/2744725/102502674-33433980-407f-11eb-8b87-bbab516e5e3e.png)

1/ I don't understand why a footprint (square) is replaced by a rectangle instead of a slightly larger square when zoomed out.
2 / the part in red seems a bit weird : I didn't expect it
![level_od_details](https://user-images.githubusercontent.com/2744725/102502515-00994100-407f-11eb-8f4e-a7cc935fde89.png)

**Comment by xalioth** [comment]
It looks OK to me, if the footprint intersects the 3 tiles it should be like this
