### ISSUE TITLE
Filtering with time widget

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#11]
Sometimes it is not very clear about the start/stop of the time widget when we apply a filter.

for example, on the image, the stop date to select seems to be before the last bar of the histogram

![range](https://user-images.githubusercontent.com/2744725/102544836-b1bace00-40b5-11eb-9efe-2bae072e64d5.png)

**Comment by xalioth** [comment]
Fixed in 13fb6bc9d413667d63816ee97b95dc42d97cb8cc
