### ISSUE TITLE
Display of the delay processing

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#13]
the duration "-1" is located on the right instead of on the left to be sorted in ascending order

I did not get why both is displayed "-1" and "20" 

![Stellarium-Web-Online-Star-Map](https://user-images.githubusercontent.com/2744725/104036153-5a4ee000-51d3-11eb-97a0-b33fee45596c.png)

**Comment by xalioth** [comment]
Fixed in 0.2.1
