### ISSUE TITLE
Delay processing format

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#14]
When the user selects the delay processing, the format of the delay processing could be improved in the constraints section.

![image](https://user-images.githubusercontent.com/2744725/104853325-5d974980-5900-11eb-8448-1cea0be8f3a2.png)

**Comment by kabasset** [comment]
BTW, "delay processing" should be "processing delay"

**Comment by xalioth** [comment]
Fixed in fa2adacc
