### ISSUE TITLE
Add a button "zoom to fit"

### ISSUE THREAD

**Issue by kabasset** [Stellarium-Labs/smt#19]
Would be nice to have a button to move the view to the selected region (+ some margin?).
Layers with opacity = 0% should be excluded.

**Comment by christophedabin** [comment]
selection (button : Search for ...) to be on : ObservationId / TileIndex / SkyPatch  correct syntax of these objects to be defined by JC depending on the properties redefined. Thanks

**Comment by xalioth** [comment]
Christophe, I copied your comment in a separated issue  #22

**Comment by xalioth** [comment]
The way I understood this is that we need to button to adjust view to fit all geojson content, not only selected items.

**Comment by xalioth** [comment]
Added in 0.3.2
