### ISSUE TITLE
Error message after applying a constraint on CreationDate

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#2]
In some cases, when I filter on "Creation Date" and I apply the constrain, I get an error in the updated histogram
![Screenshot from 2020-11-26 13-33-12](https://user-images.githubusercontent.com/2744725/100351674-1bcae080-2fec-11eb-8135-3cd380389c10.png)
![Screenshot from 2020-11-26 13-33-23](https://user-images.githubusercontent.com/2744725/100351685-208f9480-2fec-11eb-81d9-70d33d478734.png)

**Comment by xalioth** [comment]
Fixed in 0.0.8
