### ISSUE TITLE
The loading icon does not stop and constraints are not refreshed

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#20]
![image](https://user-images.githubusercontent.com/2744725/104977969-2197dd80-5a01-11eb-832f-134d8a6d1565.png)

**Comment by xalioth** [comment]
Thanks, I cannot reproduce.. when something like this appears please try to copy paste the content of the JS console, as it's usually linked with a JS error.

**Comment by xalioth** [comment]
Cannot reproduce
