### ISSUE TITLE
Selection of a list of identifiers

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#25]
I would like to select a subset of skypatch to supervise from all possible skypatches. There are about 200 skypatches and I can't see myself selecting them one by one. I think that the skypatches to select are contiguous but for other fields this will not be the case all the time. 

So, would it be possible to have a widget configured on an element of the GeoJson model : 
- Then the user provides a list of identifier that interest me in  a text area where copy/paste is allowed on this widget
- or the user uploads a list of identifiers to initiate the list if copy/paste is not allowed
- or something equivalent but **simply and quickly configurable**

**Comment by xalioth** [comment]
Done in 0.3.3
