### ISSUE TITLE
reloading of the layers

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#26]
When I select the telescope Name as Euclid, the GUI is redrawn. Then, I select the telescope Name as LSST, the GUI is redrawn.

Then, when I remove the constraint on LSST,  the GUI is redrawn then I only drop information. That's pitty but it is just a detail.

**Comment by xalioth** [comment]
I don't think I will fix this. This issue is now much less relevant because of aggressive caching.
