### ISSUE TITLE
Error when building the docker

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#3]
malapert@heulet-HP-ZBook-15-G4:~/smt_data/code/smt/smt-server$ make
# Build docker image for node development
docker build -t smt-server --build-arg USER_UID=1001 --build-arg USER_GID=1001 .
Sending build context to Docker daemon  175.1kB
Step 1/10 : FROM node:14.15.0-stretch
14.15.0-stretch: Pulling from library/node
0400ac8f7460: Pull complete 
fa8559aa5ebb: Pull complete 
da32bfbbc3ba: Pull complete 
e1dc6725529d: Pull complete 
572866ab72a6: Pull complete 
63ee7d0b743d: Pull complete 
81a57610b526: Pull complete 
8aa72b0fc009: Pull complete 
caec757d11e1: Pull complete 
Digest: sha256:b8abfe5f5d3becb03ce1c157488dd487f82d895091aeabf2f8267a87778f848b
Status: Downloaded newer image for node:14.15.0-stretch
 ---> b90fa0d7cbd1
Step 2/10 : EXPOSE 8100
 ---> Running in 3cdaf6441c36
Removing intermediate container 3cdaf6441c36
 ---> cde4c8aefbd0
Step 3/10 : RUN apt-get update && apt-get install -y libcurl3-gnutls ca-certificates
 ---> Running in d17c85a87584
Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://security.debian.org/debian-security stretch/updates InRelease [53.0 kB]
Get:3 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [2410 B]
Get:6 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [627 kB]
Get:7 http://deb.debian.org/debian stretch-updates/main amd64 Packages [2596 B]
Get:8 http://deb.debian.org/debian stretch/main amd64 Packages [7080 kB]
Fetched 7976 kB in 4s (1675 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
ca-certificates is already the newest version (20200601~deb9u1).
libcurl3-gnutls is already the newest version (7.52.1-5+deb9u12).
libcurl3-gnutls set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
Removing intermediate container d17c85a87584
 ---> 5981a84a96d7
Step 4/10 : WORKDIR /app
 ---> Running in 6f1a4177a0a2
Removing intermediate container 6f1a4177a0a2
 ---> 68df5f91794d
Step 5/10 : ENV LANG C.UTF-8
 ---> Running in 9bc4a7eb8e34
Removing intermediate container 9bc4a7eb8e34
 ---> e241de166b86
Step 6/10 : ENV LC_ALL C.UTF-8
 ---> Running in 21c431fd6fd1
Removing intermediate container 21c431fd6fd1
 ---> b793e7b4e281
Step 7/10 : RUN chown node /app
 ---> Running in a09e897a6dfd
Removing intermediate container a09e897a6dfd
 ---> eca2f8cf45cc
Step 8/10 : USER node
 ---> Running in 026493f38afb
Removing intermediate container 026493f38afb
 ---> e78d324aa0af
Step 9/10 : RUN id node
 ---> Running in dd345cbfa655
uid=1000(node) gid=1000(node) groups=1000(node)
Removing intermediate container dd345cbfa655
 ---> 65ec3b787597
Step 10/10 : CMD npm install && npm start
 ---> Running in 37b682955c72
Removing intermediate container 37b682955c72
 ---> cbd692e442dc
[Warning] One or more build-args [USER_GID USER_UID] were not consumed
Successfully built cbd692e442dc
Successfully tagged smt-server:latest
docker run -it -v "/home/malapert/smt_data/code/smt/smt-server:/app" smt-server npm install
npm WARN checkPermissions Missing write access to /app
npm WARN smt-server@0.0.3 No repository field.

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /app
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/app'
npm ERR!  [Error: EACCES: permission denied, access '/app'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/app'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-11-26T16_44_02_398Z-debug.log
Makefile:14: recipe for target 'setup' failed
make: *** [setup] Error 243

**Comment by xalioth** [comment]
Fixed in 0.0.6
