### ISSUE TITLE
Addition of contextual help

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#5]
It would be interesting to add contextual help on the GUI for the user to explain the meaning of the criteria and its associated values.

Proposal: adding a help attribute for each criterion. 

Ideally: allow the person configuring the application to be able to perform a simple formatting of the contextual help text (like markdown)

**Comment by xalioth** [comment]
Done in 0.2.1. You will need to specify the description for each fields in the smtConfig.json file.
