### ISSUE TITLE
problem when filtering is applied on the "delay processing" constraint

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#7]
Here is the use case to reproduce the problem :

1/ load SMT

2/ Apply on the fly "the delay processing" => OK
![Screenshot from 2020-12-17 15-13-44](https://user-images.githubusercontent.com/2744725/102498888-d34a9400-407a-11eb-9b8b-be556c07e93f.png)

3/Add the constraint by clinking on 'ADD' => NOK, the GUI seems blocked on the loading step
![Screenshot from 2020-12-17 15-13-52](https://user-images.githubusercontent.com/2744725/102498943-e493a080-407a-11eb-9de7-4631733b74cf.png)

**Comment by xalioth** [comment]
Fixed in 0.0.9
