### ISSUE TITLE
Problem when counting the values according to the time

### ISSUE THREAD

**Issue by J-Christophe** [Stellarium-Labs/smt#8]
The use case  

1/ Run SMT

2/ Filering the scheduled date based on the histogram => No data is displayed despite the presence of data in the histogram.
![Screenshot from 2020-12-17 15-25-12](https://user-images.githubusercontent.com/2744725/102500314-794ace00-407c-11eb-9b9c-5ebc9e8a1b8b.png)

3/ Add the constraint => still no data
![Screenshot from 2020-12-17 15-25-24](https://user-images.githubusercontent.com/2744725/102500447-9ed7d780-407c-11eb-903b-f78ef9989866.png)

**Comment by xalioth** [comment]
I just realized that the histogram misses columns without any item, e.g. it jumps from 2018 to 2021 if nothing was observed in 2019 and 2020
I will fix that later this week

**Comment by xalioth** [comment]
Fixed in 0.0.8
